import Head from "next/head";
import Home from "../components/Home";

export default function App() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Ha Noi Garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  );
}
