import Head from "next/head";
import Header from "../components/Header";

const Product = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Sản phẩm </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  );
};

export default Product;
