import Head from "next/head";
import ProductContainer from "../components/ProductContainer";

const Product = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Sản phẩm </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductContainer />
    </div>
  );
};

export default Product;
